/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/account/confirm-email/': RouteRecordInfo<
      '/account/confirm-email/',
      '/account/confirm-email',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/account/confirm-email/confirmed': RouteRecordInfo<
      '/account/confirm-email/confirmed',
      '/account/confirm-email/confirmed',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/account/create': RouteRecordInfo<
      '/account/create',
      '/account/create',
      Record<never, never>,
      Record<never, never>,
      | '/account/create/'
      | '/account/create/check-email'
      | '/account/create/confirm-email'
      | '/account/create/create-account'
      | '/account/create/create-firm'
      | '/account/create/personal-info'
      | '/account/create/protect-account'
      | '/account/create/review-firms'
    >,
    '/account/create/': RouteRecordInfo<
      '/account/create/',
      '/account/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/account/create/check-email': RouteRecordInfo<
      '/account/create/check-email',
      '/account/create/check-email',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/account/create/confirm-email': RouteRecordInfo<
      '/account/create/confirm-email',
      '/account/create/confirm-email',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/account/create/create-account': RouteRecordInfo<
      '/account/create/create-account',
      '/account/create/create-account',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/account/create/create-firm': RouteRecordInfo<
      '/account/create/create-firm',
      '/account/create/create-firm',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/account/create/personal-info': RouteRecordInfo<
      '/account/create/personal-info',
      '/account/create/personal-info',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/account/create/protect-account': RouteRecordInfo<
      '/account/create/protect-account',
      '/account/create/protect-account',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/account/create/review-firms': RouteRecordInfo<
      '/account/create/review-firms',
      '/account/create/review-firms',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/account/login/': RouteRecordInfo<
      '/account/login/',
      '/account/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/account/logout/': RouteRecordInfo<
      '/account/logout/',
      '/account/logout',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/clients/': RouteRecordInfo<
      '/clients/',
      '/clients',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/clients/[id]': RouteRecordInfo<
      '/clients/[id]',
      '/clients/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/clients/internals/ClientDetailActive': RouteRecordInfo<
      '/clients/internals/ClientDetailActive',
      '/clients/internals/ClientDetailActive',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/clients/internals/ClientDetailInactive': RouteRecordInfo<
      '/clients/internals/ClientDetailInactive',
      '/clients/internals/ClientDetailInactive',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/clients/internals/ClientDetailOnboarding': RouteRecordInfo<
      '/clients/internals/ClientDetailOnboarding',
      '/clients/internals/ClientDetailOnboarding',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/clients/internals/ClientDetailReferral': RouteRecordInfo<
      '/clients/internals/ClientDetailReferral',
      '/clients/internals/ClientDetailReferral',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/clients/internals/CompletenessCard': RouteRecordInfo<
      '/clients/internals/CompletenessCard',
      '/clients/internals/CompletenessCard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/clients/internals/ProfileField': RouteRecordInfo<
      '/clients/internals/ProfileField',
      '/clients/internals/ProfileField',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/clients/internals/ProfileSection': RouteRecordInfo<
      '/clients/internals/ProfileSection',
      '/clients/internals/ProfileSection',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/clients/refer': RouteRecordInfo<
      '/clients/refer',
      '/clients/refer',
      Record<never, never>,
      Record<never, never>,
      | '/clients/refer/'
      | '/clients/refer/bulk/'
      | '/clients/refer/bulk/BulkMapping'
      | '/clients/refer/bulk/BulkReview'
      | '/clients/refer/bulk/BulkUpload'
      | '/clients/refer/bulk/internals/EditableCell'
      | '/clients/refer/bulk/internals/EditableTable'
      | '/clients/refer/bulk/success'
      | '/clients/refer/success'
    >,
    '/clients/refer/': RouteRecordInfo<
      '/clients/refer/',
      '/clients/refer',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/clients/refer/bulk/': RouteRecordInfo<
      '/clients/refer/bulk/',
      '/clients/refer/bulk',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/clients/refer/bulk/BulkMapping': RouteRecordInfo<
      '/clients/refer/bulk/BulkMapping',
      '/clients/refer/bulk/BulkMapping',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/clients/refer/bulk/BulkReview': RouteRecordInfo<
      '/clients/refer/bulk/BulkReview',
      '/clients/refer/bulk/BulkReview',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/clients/refer/bulk/BulkUpload': RouteRecordInfo<
      '/clients/refer/bulk/BulkUpload',
      '/clients/refer/bulk/BulkUpload',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/clients/refer/bulk/internals/EditableCell': RouteRecordInfo<
      '/clients/refer/bulk/internals/EditableCell',
      '/clients/refer/bulk/internals/EditableCell',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/clients/refer/bulk/internals/EditableTable': RouteRecordInfo<
      '/clients/refer/bulk/internals/EditableTable',
      '/clients/refer/bulk/internals/EditableTable',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/clients/refer/bulk/success': RouteRecordInfo<
      '/clients/refer/bulk/success',
      '/clients/refer/bulk/success',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/clients/refer/success': RouteRecordInfo<
      '/clients/refer/success',
      '/clients/refer/success',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/': RouteRecordInfo<
      '/dashboard/',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/internals/FirmDashboard': RouteRecordInfo<
      '/dashboard/internals/FirmDashboard',
      '/dashboard/internals/FirmDashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/internals/FirmSetup': RouteRecordInfo<
      '/dashboard/internals/FirmSetup',
      '/dashboard/internals/FirmSetup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/internals/FirmSetupCard': RouteRecordInfo<
      '/dashboard/internals/FirmSetupCard',
      '/dashboard/internals/FirmSetupCard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/firm-members/': RouteRecordInfo<
      '/firm-members/',
      '/firm-members',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/firm-members/[id]': RouteRecordInfo<
      '/firm-members/[id]',
      '/firm-members/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/payrolls/': RouteRecordInfo<
      '/payrolls/',
      '/payrolls',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/payrolls/[id]': RouteRecordInfo<
      '/payrolls/[id]',
      '/payrolls/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/welcome/': RouteRecordInfo<
      '/welcome/',
      '/welcome',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/welcome/internals/ToutList': RouteRecordInfo<
      '/welcome/internals/ToutList',
      '/welcome/internals/ToutList',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'src/pages/account/confirm-email/index.vue': {
      routes:
        | '/account/confirm-email/'
      views:
        | never
    }
    'src/pages/account/confirm-email/confirmed.vue': {
      routes:
        | '/account/confirm-email/confirmed'
      views:
        | never
    }
    'src/pages/account/create.vue': {
      routes:
        | '/account/create'
        | '/account/create/'
        | '/account/create/check-email'
        | '/account/create/confirm-email'
        | '/account/create/create-account'
        | '/account/create/create-firm'
        | '/account/create/personal-info'
        | '/account/create/protect-account'
        | '/account/create/review-firms'
      views:
        | 'default'
    }
    'src/pages/account/create/index.vue': {
      routes:
        | '/account/create/'
      views:
        | never
    }
    'src/pages/account/create/check-email.vue': {
      routes:
        | '/account/create/check-email'
      views:
        | never
    }
    'src/pages/account/create/confirm-email.vue': {
      routes:
        | '/account/create/confirm-email'
      views:
        | never
    }
    'src/pages/account/create/create-account.vue': {
      routes:
        | '/account/create/create-account'
      views:
        | never
    }
    'src/pages/account/create/create-firm.vue': {
      routes:
        | '/account/create/create-firm'
      views:
        | never
    }
    'src/pages/account/create/personal-info.vue': {
      routes:
        | '/account/create/personal-info'
      views:
        | never
    }
    'src/pages/account/create/protect-account.vue': {
      routes:
        | '/account/create/protect-account'
      views:
        | never
    }
    'src/pages/account/create/review-firms.vue': {
      routes:
        | '/account/create/review-firms'
      views:
        | never
    }
    'src/pages/account/login/index.vue': {
      routes:
        | '/account/login/'
      views:
        | never
    }
    'src/pages/account/logout/index.vue': {
      routes:
        | '/account/logout/'
      views:
        | never
    }
    'src/pages/clients/index.vue': {
      routes:
        | '/clients/'
      views:
        | never
    }
    'src/pages/clients/[id].vue': {
      routes:
        | '/clients/[id]'
      views:
        | never
    }
    'src/pages/clients/internals/ClientDetailActive.vue': {
      routes:
        | '/clients/internals/ClientDetailActive'
      views:
        | never
    }
    'src/pages/clients/internals/ClientDetailInactive.vue': {
      routes:
        | '/clients/internals/ClientDetailInactive'
      views:
        | never
    }
    'src/pages/clients/internals/ClientDetailOnboarding.vue': {
      routes:
        | '/clients/internals/ClientDetailOnboarding'
      views:
        | never
    }
    'src/pages/clients/internals/ClientDetailReferral.vue': {
      routes:
        | '/clients/internals/ClientDetailReferral'
      views:
        | never
    }
    'src/pages/clients/internals/CompletenessCard.vue': {
      routes:
        | '/clients/internals/CompletenessCard'
      views:
        | never
    }
    'src/pages/clients/internals/ProfileField.vue': {
      routes:
        | '/clients/internals/ProfileField'
      views:
        | never
    }
    'src/pages/clients/internals/ProfileSection.vue': {
      routes:
        | '/clients/internals/ProfileSection'
      views:
        | never
    }
    'src/pages/clients/refer.vue': {
      routes:
        | '/clients/refer'
        | '/clients/refer/'
        | '/clients/refer/bulk/'
        | '/clients/refer/bulk/BulkMapping'
        | '/clients/refer/bulk/BulkReview'
        | '/clients/refer/bulk/BulkUpload'
        | '/clients/refer/bulk/internals/EditableCell'
        | '/clients/refer/bulk/internals/EditableTable'
        | '/clients/refer/bulk/success'
        | '/clients/refer/success'
      views:
        | 'default'
    }
    'src/pages/clients/refer/index.vue': {
      routes:
        | '/clients/refer/'
      views:
        | never
    }
    'src/pages/clients/refer/bulk/index.vue': {
      routes:
        | '/clients/refer/bulk/'
      views:
        | never
    }
    'src/pages/clients/refer/bulk/BulkMapping.vue': {
      routes:
        | '/clients/refer/bulk/BulkMapping'
      views:
        | never
    }
    'src/pages/clients/refer/bulk/BulkReview.vue': {
      routes:
        | '/clients/refer/bulk/BulkReview'
      views:
        | never
    }
    'src/pages/clients/refer/bulk/BulkUpload.vue': {
      routes:
        | '/clients/refer/bulk/BulkUpload'
      views:
        | never
    }
    'src/pages/clients/refer/bulk/internals/EditableCell.vue': {
      routes:
        | '/clients/refer/bulk/internals/EditableCell'
      views:
        | never
    }
    'src/pages/clients/refer/bulk/internals/EditableTable.vue': {
      routes:
        | '/clients/refer/bulk/internals/EditableTable'
      views:
        | never
    }
    'src/pages/clients/refer/bulk/success.vue': {
      routes:
        | '/clients/refer/bulk/success'
      views:
        | never
    }
    'src/pages/clients/refer/success.vue': {
      routes:
        | '/clients/refer/success'
      views:
        | never
    }
    'src/pages/dashboard/index.vue': {
      routes:
        | '/dashboard/'
      views:
        | never
    }
    'src/pages/dashboard/internals/FirmDashboard.vue': {
      routes:
        | '/dashboard/internals/FirmDashboard'
      views:
        | never
    }
    'src/pages/dashboard/internals/FirmSetup.vue': {
      routes:
        | '/dashboard/internals/FirmSetup'
      views:
        | never
    }
    'src/pages/dashboard/internals/FirmSetupCard.vue': {
      routes:
        | '/dashboard/internals/FirmSetupCard'
      views:
        | never
    }
    'src/pages/firm-members/index.vue': {
      routes:
        | '/firm-members/'
      views:
        | never
    }
    'src/pages/firm-members/[id].vue': {
      routes:
        | '/firm-members/[id]'
      views:
        | never
    }
    'src/pages/payrolls/index.vue': {
      routes:
        | '/payrolls/'
      views:
        | never
    }
    'src/pages/payrolls/[id].vue': {
      routes:
        | '/payrolls/[id]'
      views:
        | never
    }
    'src/pages/welcome/index.vue': {
      routes:
        | '/welcome/'
      views:
        | never
    }
    'src/pages/welcome/internals/ToutList.vue': {
      routes:
        | '/welcome/internals/ToutList'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
