/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/account/confirm-email/': RouteRecordInfo<
      '/account/confirm-email/',
      '/account/confirm-email',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/account/confirm-email/confirmed': RouteRecordInfo<
      '/account/confirm-email/confirmed',
      '/account/confirm-email/confirmed',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/account/create': RouteRecordInfo<
      '/account/create',
      '/account/create',
      Record<never, never>,
      Record<never, never>,
      | '/account/create/'
      | '/account/create/check-email'
      | '/account/create/confirm-email'
      | '/account/create/create-account'
      | '/account/create/create-firm'
      | '/account/create/personal-info'
      | '/account/create/protect-account'
      | '/account/create/review-firms'
    >,
    '/account/create/': RouteRecordInfo<
      '/account/create/',
      '/account/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/account/create/check-email': RouteRecordInfo<
      '/account/create/check-email',
      '/account/create/check-email',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/account/create/confirm-email': RouteRecordInfo<
      '/account/create/confirm-email',
      '/account/create/confirm-email',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/account/create/create-account': RouteRecordInfo<
      '/account/create/create-account',
      '/account/create/create-account',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/account/create/create-firm': RouteRecordInfo<
      '/account/create/create-firm',
      '/account/create/create-firm',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/account/create/personal-info': RouteRecordInfo<
      '/account/create/personal-info',
      '/account/create/personal-info',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/account/create/protect-account': RouteRecordInfo<
      '/account/create/protect-account',
      '/account/create/protect-account',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/account/create/review-firms': RouteRecordInfo<
      '/account/create/review-firms',
      '/account/create/review-firms',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/account/login/': RouteRecordInfo<
      '/account/login/',
      '/account/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/account/logout/': RouteRecordInfo<
      '/account/logout/',
      '/account/logout',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/clients/': RouteRecordInfo<
      '/clients/',
      '/clients',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/clients/[id]': RouteRecordInfo<
      '/clients/[id]',
      '/clients/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/clients/refer': RouteRecordInfo<
      '/clients/refer',
      '/clients/refer',
      Record<never, never>,
      Record<never, never>,
      | '/clients/refer/'
      | '/clients/refer/additional-context'
      | '/clients/refer/company-contact'
      | '/clients/refer/company-details'
    >,
    '/clients/refer/': RouteRecordInfo<
      '/clients/refer/',
      '/clients/refer',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/clients/refer/additional-context': RouteRecordInfo<
      '/clients/refer/additional-context',
      '/clients/refer/additional-context',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/clients/refer/company-contact': RouteRecordInfo<
      '/clients/refer/company-contact',
      '/clients/refer/company-contact',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/clients/refer/company-details': RouteRecordInfo<
      '/clients/refer/company-details',
      '/clients/refer/company-details',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/clients/refer-bulk/': RouteRecordInfo<
      '/clients/refer-bulk/',
      '/clients/refer-bulk',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/': RouteRecordInfo<
      '/dashboard/',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/internals/FirmSetup': RouteRecordInfo<
      '/dashboard/internals/FirmSetup',
      '/dashboard/internals/FirmSetup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/internals/FirmSetupCard': RouteRecordInfo<
      '/dashboard/internals/FirmSetupCard',
      '/dashboard/internals/FirmSetupCard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/firm-members/': RouteRecordInfo<
      '/firm-members/',
      '/firm-members',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/firm-members/[id]': RouteRecordInfo<
      '/firm-members/[id]',
      '/firm-members/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/welcome/': RouteRecordInfo<
      '/welcome/',
      '/welcome',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/welcome/internals/ToutList': RouteRecordInfo<
      '/welcome/internals/ToutList',
      '/welcome/internals/ToutList',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'src/pages/account/confirm-email/index.vue': {
      routes:
        | '/account/confirm-email/'
      views:
        | never
    }
    'src/pages/account/confirm-email/confirmed.vue': {
      routes:
        | '/account/confirm-email/confirmed'
      views:
        | never
    }
    'src/pages/account/create.vue': {
      routes:
        | '/account/create'
        | '/account/create/'
        | '/account/create/check-email'
        | '/account/create/confirm-email'
        | '/account/create/create-account'
        | '/account/create/create-firm'
        | '/account/create/personal-info'
        | '/account/create/protect-account'
        | '/account/create/review-firms'
      views:
        | 'default'
    }
    'src/pages/account/create/index.vue': {
      routes:
        | '/account/create/'
      views:
        | never
    }
    'src/pages/account/create/check-email.vue': {
      routes:
        | '/account/create/check-email'
      views:
        | never
    }
    'src/pages/account/create/confirm-email.vue': {
      routes:
        | '/account/create/confirm-email'
      views:
        | never
    }
    'src/pages/account/create/create-account.vue': {
      routes:
        | '/account/create/create-account'
      views:
        | never
    }
    'src/pages/account/create/create-firm.vue': {
      routes:
        | '/account/create/create-firm'
      views:
        | never
    }
    'src/pages/account/create/personal-info.vue': {
      routes:
        | '/account/create/personal-info'
      views:
        | never
    }
    'src/pages/account/create/protect-account.vue': {
      routes:
        | '/account/create/protect-account'
      views:
        | never
    }
    'src/pages/account/create/review-firms.vue': {
      routes:
        | '/account/create/review-firms'
      views:
        | never
    }
    'src/pages/account/login/index.vue': {
      routes:
        | '/account/login/'
      views:
        | never
    }
    'src/pages/account/logout/index.vue': {
      routes:
        | '/account/logout/'
      views:
        | never
    }
    'src/pages/clients/index.vue': {
      routes:
        | '/clients/'
      views:
        | never
    }
    'src/pages/clients/[id].vue': {
      routes:
        | '/clients/[id]'
      views:
        | never
    }
    'src/pages/clients/refer.vue': {
      routes:
        | '/clients/refer'
        | '/clients/refer/'
        | '/clients/refer/additional-context'
        | '/clients/refer/company-contact'
        | '/clients/refer/company-details'
      views:
        | 'default'
    }
    'src/pages/clients/refer/index.vue': {
      routes:
        | '/clients/refer/'
      views:
        | never
    }
    'src/pages/clients/refer/additional-context.vue': {
      routes:
        | '/clients/refer/additional-context'
      views:
        | never
    }
    'src/pages/clients/refer/company-contact.vue': {
      routes:
        | '/clients/refer/company-contact'
      views:
        | never
    }
    'src/pages/clients/refer/company-details.vue': {
      routes:
        | '/clients/refer/company-details'
      views:
        | never
    }
    'src/pages/clients/refer-bulk/index.vue': {
      routes:
        | '/clients/refer-bulk/'
      views:
        | never
    }
    'src/pages/dashboard/index.vue': {
      routes:
        | '/dashboard/'
      views:
        | never
    }
    'src/pages/dashboard/internals/FirmSetup.vue': {
      routes:
        | '/dashboard/internals/FirmSetup'
      views:
        | never
    }
    'src/pages/dashboard/internals/FirmSetupCard.vue': {
      routes:
        | '/dashboard/internals/FirmSetupCard'
      views:
        | never
    }
    'src/pages/firm-members/index.vue': {
      routes:
        | '/firm-members/'
      views:
        | never
    }
    'src/pages/firm-members/[id].vue': {
      routes:
        | '/firm-members/[id]'
      views:
        | never
    }
    'src/pages/welcome/index.vue': {
      routes:
        | '/welcome/'
      views:
        | never
    }
    'src/pages/welcome/internals/ToutList.vue': {
      routes:
        | '/welcome/internals/ToutList'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
